env: "local"
database: # postgresql://<username>:<password>@<host>:<port>/<dbname>?sslmode=<sslmode>
  username:
  password:
  address:
  port:
  dbName:
  sslmode:
http_server: 
  address: # ip server
  port:  # port server
  timeout: # default 4s
  idle_timeout: #default 30s
jwt:
  secretKey: # private key